name: Bug Report
description: Reporte um bug ou problema
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Preencha as informações abaixo para nos ajudar a resolver o problema.

  - type: input
    id: php-version
    attributes:
      label: Versão do PHP
      placeholder: "ex: 8.3.0"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Versão do Laravel
      placeholder: "ex: 12.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Versão do Pacote
      placeholder: "ex: 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva o bug de forma clara e concisa
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: |
        Passos para reproduzir o comportamento:
        1. Vá para '...'
        2. Clique em '....'
        3. Role para baixo até '....'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: Descreva o que você esperava que acontecesse
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Se aplicável, adicione screenshots para ajudar a explicar o problema

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Adicione qualquer outra informação sobre o problema aqui
